name: CI on Master
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  create-new-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create and Push new tag
        shell: pwsh
        run: |
         . ./Scripts/VersionManager.ps1
         New-Tag -Branch "master" -SourceBranch "${{ github.head_ref }}"